# Generated by Django 5.1.6 on 2025-04-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dept',
            new_name='department',
        ),
    ]
