# Generated by Django 5.1.6 on 2025-04-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_dept_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
