# Generated by Django 5.1.6 on 2025-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patient_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
